app <- ShinyDriver$new("../")
app$snapshotInit("built_test")

# Input '`shinyjs-resettable-Dapp`' was set, but doesn't have an input binding.
app$setInputs(checkbox = TRUE)
app$setInputs(load = "click")
app$snapshot()
app$setInputs(sel_d = "1")
app$setInputs(update = "click")
app$snapshot()
app$setInputs(accuracy_del = "2")
app$setInputs(update = "click")
app$setInputs(perc_error = character(0))
app$setInputs(perc_error = 15)
app$setInputs(update = "click")
app$snapshot()
app$setInputs(sbjFast_del = "2")
app$setInputs(update = "click")
app$snapshot()
app$setInputs(accuracy_del = "1")
app$setInputs(sbjFast_del = "1")
app$setInputs(update = "click")
app$snapshot()
app$setInputs(point_opts = "2")
app$snapshot()
app$setInputs(point_opts = "3")
app$snapshot()
app$setInputs(graph = "2")
app$snapshot()
app$setInputs(graph = "3")
app$snapshot()
app$setInputs(graph = "4")
app$snapshot()
app$setInputs(reset = "click")
# Input '`shinyjs-resettable-Dapp`' was set, but doesn't have an input binding.
app$snapshot()
